### ISSUE TITLE
Create python implementations for Constants

### ISSUE THREAD

**Issue by SpaceDevz** [Zconj095/EdgeLore_Language#1]
So we can use the constants easier we should create a `python implementation` of all of the constants. Something like the following will suffice.

```py
class Frequency(...):
    def __init__(self):
        self.repr = "int" # Just an example.
```

This will allow me to do something like this:

```py
from ConstantImplementations import Frequency, ...

class FREQUENCY_CLASSES:
  """Classs definition created by EdgeLore
     Creation Time: 0.0003120899200439453"""
  def __init__(self, alpha, beta, theta, delta, gamma):
      self.alpha: Frequency = None
      ...
```

**Comment by SpaceDevz** [comment]
Looking at how many constants there is, this will be a tedious task haha.

**Comment by SpaceDevz** [comment]
Figure out a way to do it without this, I believe.

**Comment by Zconj095** [comment]
This would work more efficiently if we could manipulate the constants the same as keywords from a library on VS code or Notepad++. If it is within the system it can be used word by word. I am seriously impressed. Sorry for such a late response. I just saw the notification that was made in October. If used similar to keywords then the use of constants in a specific order will activate in a sense of cause and effect. I have been busy myself searching and filtering out the language for as many errors as I could.
